#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
set -o pipefail
LC_ALL=C
if [[ $USER != root ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
fid-apt-repository -y ppa:xubuntu-dev/xfce-4.10
apt -q update
apt -y install xubuntu-desktop xfce4-composite-editor xfce-theme-manager xfce4-power-manager-plugins
apt-get clean
clear
echo -e "\e[00;1;92mFinished...\e[00m"
exit 0
